server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://open.bigmodel.cn/api/paas/v4/
      api-key: 1fae2d840b624d68b82a4890ab79ff25.wrqDRqXB3XrkzOL7
      model-name: glm-4.5-air
      temperature: 0.7
      max-tokens: 4000
      timeout: 60s
    streaming-chat-model:
      base-url: https://open.bigmodel.cn/api/paas/v4/
      api-key: 1fae2d840b624d68b82a4890ab79ff25.wrqDRqXB3XrkzOL7
      model-name: glm-4.5-air
      temperature: 0.7
      max-tokens: 4000
      timeout: 60s
    embedding-model:
      base-url: https://open.bigmodel.cn/api/paas/v4/
      api-key: 1fae2d840b624d68b82a4890ab79ff25.wrqDRqXB3XrkzOL7
      model-name: embedding-3

spring:
  application:
    name: sky-ai-service
  data:
    redis:
      database: 2
      port: 6379
      host: localhost
