---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 26910.
--- DateTime: 2026/5/4 18:03
---
-- KEYS[1] ：缓存键，如 "daily:dishes"
-- ARGV     ：前 n-1 个元素是菜品名称，最后一个元素是过期秒数

redis.call('DEL', KEYS[1])

-- 按顺序 LPUSH，保持与 leftPushAll 相同的结果
for i = 1, #ARGV - 1 do
    redis.call('LPUSH', KEYS[1], ARGV[i])
end

-- 如果有参数，设置过期时间
-- （ARGV 至少包含一个过期秒数，否则不会执行）
if #ARGV > 0 then
    redis.call('EXPIRE', KEYS[1], ARGV[#ARGV])
end

return 1   -- 返回成功标志（可根据需要返回列表长度等）